const el=id=>document.getElementById(id);
const cardsEl=el('cards'),q=el('q'),fb=el('feedback'),emptyEl=el('empty'),todayTextEl=el('todayText'),n1El=el('n1'),t1El=el('t1'),n2El=el('n2'),t2El=el('t2'),favListEl=el('favList'),copyKeyEl=el('copyKey'),pixKeyEl=el('pixKey'),shareEl=el('share'),nearEl=el('near'),subwrap=el('subwrap'),subchips=el('subchips'),subhead=el('subhead'),guideTitle=el('guideTitle'),guideSub=el('guideSub'),clearSearchEl=el('clearSearch'),searchHintEl=el('searchHint');
const D=(window.MA_CARDS||[]).map((c,i)=>({...c,_i:i}));let cat='destaques',sub='all',day='all';
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const esc=s=>(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const textOf=c=>norm(c.t+' '+c.d+' '+c.g+' '+(c.h||'')+' '+(c.p||''));
const has=(c,words)=>{const z=textOf(c);return words.some(w=>z.includes(norm(w)))};
const FEATURED=['Centro Histórico de São Luís','Palácio dos Leões','Museu do Reggae Maranhão','Mercado das Tulhas','Espigão Costeiro','Parque do Rangedor','Cabana do Sol','Flor de Vinagreira','Barraca da Marcela','Bar do Nelson','Lençóis Maranhenses','Alcântara','Tutóia & Delta','Lagoa do Cassó','Chapada das Mesas'];
const SUBS={
 turismo:[['all','Tudo para conhecer'],['centro','🏛️ Centro Histórico'],['cultura','🎭 Cultura & patrimônio'],['museu','🏛️ Museus'],['praia','🏖️ Praias & orla'],['por-do-sol','🌅 Pôr do sol'],['lendas','👻 Lendas']],
 comer:[['all','Tudo em Comer'],['regional','🌴 Maranhense'],['frutos','🐟 Peixes & frutos do mar'],['caranguejo','🦀 Caranguejo'],['centro','🏛️ Centro Histórico'],['orla','🌊 Litorânea / Calhau'],['cafe','☕ Cafés'],['sorvete','🍦 Sorvetes'],['casal','❤️ Casal'],['familia','👨‍👩‍👧 Família']],
 noite:[['all','Toda a noite'],['reggae','🇯🇲 Reggae'],['samba','🥁 Samba & pagode'],['pub','🎸 Pubs & música ao vivo'],['centro','🏛️ Centro'],['orla','🌊 Litorânea / Calhau']],
 reggae:[['all','Todo o reggae'],['centro','🏛️ Centro'],['orla','🌊 Litorânea'],['museu','🏛️ Museu do Reggae']],
 criancas:[['all','Tudo com crianças'],['parque','🌳 Parques'],['praia','🏖️ Praia & ar livre'],['indoor','☔ Coberto / shopping']],
 lendas:[['all','Todas as lendas'],['centro','🏛️ Mistérios do Centro'],['ilha','🌊 Lendas da Ilha']],
 maranhao:[['all','Todo o Maranhão'],['perto','🚗 Perto de São Luís'],['lencois','🏜️ Lençóis'],['delta','🛶 Tutóia & Delta'],['casso','💎 Lagoa do Cassó'],['munim','💧 Munim & rios'],['chapada','🏞️ Chapada'],['guaras','🦜 Guarás / litoral oeste']]
};
const GROUP_DESCS={
 '🚗 Perto de São Luís / Grande Ilha':'Passeios que combinam melhor com uma estadia na capital.',
 '🏜️ Lençóis Maranhenses':'Bases e destinos ligados ao Parque Nacional e ao litoral dos Lençóis.',
 '🛶 Tutóia, Delta & litoral oriental':'Tutóia em destaque junto aos destinos do Delta das Américas.',
 '💎 Lagoa do Cassó & Primeira Cruz':'Destino lindo, mas com atenção especial à logística de acesso.',
 '💧 Rios & Polo Munim':'Natureza, rios e balneários fora do roteiro mais óbvio.',
 '🏞️ Chapada das Mesas':'Uma viagem própria para o sul do Maranhão.',
 '🦜 Floresta dos Guarás / litoral oeste':'Destinos mais remotos e de logística específica.',
 '👻 Mistérios do Centro Histórico':'Lendas ligadas às ruas, praças e fontes do Centro.',
 '🌊 Lendas da Ilha':'Histórias ligadas a outros pontos da Ilha de São Luís.'
};
function matchesCat(c,k){const tags=norm(c.g).split(/\s+/);if(k==='destaques')return FEATURED.some(x=>norm(c.t).includes(norm(x)));if(k==='all')return true;if(k==='reggae')return tags.includes('reggae');if(k==='noite')return tags.includes('noite')||tags.includes('reggae');if(k==='lendas')return tags.includes('lendas')||has(c,['serpente encantada','ana jansen','manguda','olho dagua']);return tags.includes(k)}
function matchesSub(c,k){if(k==='all')return true;const z=textOf(c);const map={
 centro:['centro','praia grande','reviver'],cultura:['cultura','historia','patrimonio','igreja','afro','quilombo'],museu:['museu'],praia:['praia','orla','litoranea'],'por-do-sol':['por-do-sol','por do sol'],lendas:['lendas','serpente','ana jansen','manguda'],ilha:['olho dagua','olho d agua','mae dagua'],
 regional:['maranhense','regional','nordestino','cuxa','jucara'],frutos:['frutos mar','peixe','camarao','bacalhau','marisco'],caranguejo:['caranguejo','caranguejada'],orla:['litoranea','calhau','ponta dareia','ponta d areia','ponta farol','sao marcos'],cafe:['cafe','caffè'],sorvete:['sorvete','gelato'],casal:['casal'],familia:['familia','grupo'],
 reggae:['reggae'],samba:['samba','pagode'],pub:['pub','rock','blues','musica ao vivo'],parque:['parque'],indoor:['shopping','indoor','chuva','danny'],
 perto:['alcantara','raposa','ribamar','paco lumiar','grande ilha'],lencois:['lencois','barreirinhas','santo amaro','atins'],delta:['tutoia','delta','araioses','agua doce','paulino neves','arpoador'],casso:['casso','primeira cruz'],munim:['morros','munim','rio una'],chapada:['chapada','carolina','riachao'],guaras:['guaras','cururupu','guimaraes','floresta dos guaras']};return (map[k]||[]).some(w=>z.includes(norm(w)))}
function catMatch(c){return matchesCat(c,cat)}
function subMatch(c){return matchesSub(c,sub)}
function dayMatch(c){if(day==='all')return true;const d=c.y||'all';return d==='all'||String(d).split(',').includes(day)}
function queryMatch(c,raw){const terms=norm(raw).trim().split(/\s+/).filter(Boolean);if(!terms.length)return true;const z=textOf(c);return terms.every(t=>z.includes(t))}
function groupFor(c){if(cat==='maranhao'){if(has(c,['casso','primeira cruz']))return[3,'💎 Lagoa do Cassó & Primeira Cruz'];if(has(c,['tutoia','delta','araioses','agua doce','paulino neves','arpoador']))return[2,'🛶 Tutóia, Delta & litoral oriental'];if(has(c,['lencois','barreirinhas','santo amaro','atins']))return[1,'🏜️ Lençóis Maranhenses'];if(has(c,['alcantara','raposa','ribamar','paco lumiar','grande ilha']))return[0,'🚗 Perto de São Luís / Grande Ilha'];if(has(c,['morros','munim','rio una']))return[4,'💧 Rios & Polo Munim'];if(has(c,['chapada','carolina','riachao']))return[5,'🏞️ Chapada das Mesas'];if(has(c,['guaras','cururupu','guimaraes']))return[6,'🦜 Floresta dos Guarás / litoral oeste'];return[7,'🌴 Outros destinos do Maranhão']}
 if(cat==='comer'){if(has(c,['cafe','caffè']))return[5,'☕ Cafés'];if(has(c,['sorvete','gelato']))return[6,'🍦 Sorvetes'];if(has(c,['caranguejo','caranguejada']))return[2,'🦀 Caranguejo'];if(has(c,['maranhense','regional','cuxa','jucara']))return[0,'🌴 Comida maranhense'];if(has(c,['frutos mar','peixe','camarao','bacalhau']))return[1,'🐟 Peixes & frutos do mar'];if(has(c,['centro','praia grande','reviver']))return[3,'🏛️ Onde comer no Centro Histórico'];if(has(c,['litoranea','calhau','ponta dareia','ponta farol']))return[4,'🌊 Litorânea / Calhau / Ponta d’Areia'];return[7,'🍽️ Outros restaurantes']}
 if(cat==='turismo'){if(has(c,['museu']))return[1,'🏛️ Museus'];if(has(c,['praia','orla','litoranea']))return[3,'🏖️ Praias & orla'];if(has(c,['por-do-sol','por do sol']))return[4,'🌅 Pôr do sol'];if(has(c,['lendas','serpente','ana jansen','manguda']))return[5,'👻 Lendas'];if(has(c,['centro','historia','patrimonio','cultura']))return[0,'🏛️ Centro Histórico & patrimônio'];return[6,'📍 Outros passeios em São Luís']}
 if(cat==='lendas'){if(has(c,['olho dagua','olho d agua','mae dagua']))return[1,'🌊 Lendas da Ilha'];return[0,'👻 Mistérios do Centro Histórico']}
 if(cat==='noite'||cat==='reggae'){if(has(c,['reggae']))return[0,'🇯🇲 Reggae'];if(has(c,['samba','pagode']))return[1,'🥁 Samba & pagode'];if(has(c,['seresta']))return[2,'🎤 Seresta'];if(has(c,['pub','rock','blues']))return[3,'🎸 Pubs & música ao vivo'];return[4,'🌙 Outras opções para a noite']}
 return[0,'']}
function searchGroup(c){const tags=norm(c.g).split(/\s+/);if(tags.includes('maranhao')&&!tags.includes('sao')&&!tags.includes('luis'))return[4,'🌴 Maranhão'];if(tags.includes('comer')||tags.includes('cafe')||tags.includes('sorvete'))return[2,'🍽️ Comer & beber'];if(tags.includes('noite')||tags.includes('reggae'))return[3,'🌙 Noite & reggae'];if(tags.includes('lendas'))return[1,'👻 Lendas'];if(tags.includes('turismo')||tags.includes('cultura'))return[0,'📍 Conhecer São Luís'];return[5,'🗂️ Outros resultados']}
function renderSubfilters(){const searching=q.value.trim().length>0;if(searching){subwrap.hidden=true;return}const defs=SUBS[cat]||[];subwrap.hidden=!defs.length;if(!defs.length){sub='all';return}subhead.textContent=cat==='maranhao'?'Escolha uma região ou destino':cat==='comer'?'Escolha o tipo de comida ou região':cat==='lendas'?'Escolha o tipo de lenda':'Refine sua escolha';subchips.innerHTML=defs.map(([k,l])=>{const n=D.filter(c=>matchesCat(c,cat)&&matchesSub(c,k)).length;return`<button class="chip${k===sub?' on':''}" type="button" data-sub="${k}">${l}<span class="sub-count">${n}</span></button>`}).join('');subchips.querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>{sub=b.dataset.sub;renderSubfilters();render(true)})}
function cardHTML(c){return`<article class="card item" data-i="${c._i}">${c.s?`<span class="st${c.a?' alert':''}">${esc(c.s)}</span>`:''}<button class="fav" type="button" aria-label="Favoritar">☆</button><h3>${esc(c.t)}</h3><p>${esc(c.d)}</p>${c.h?`<div class="hrs">${esc(c.h)}</div>`:''}${c.p?`<div class="tip">${esc(c.p)}</div>`:''}<div class="acts">${(c.l||[]).map(x=>`<a class="btn" target="_blank" rel="noopener" href="${esc(x.url)}">${esc(x.label)}</a>`).join('')}</div></article>`}
function updateMainCounts(){document.querySelectorAll('#mainCategories [data-f]').forEach(b=>{let badge=b.querySelector('.cat-count');if(!badge){badge=document.createElement('span');badge.className='cat-count';b.appendChild(badge)}badge.textContent=D.filter(c=>matchesCat(c,b.dataset.f)).length})}
function render(go=false){const raw=q.value.trim(),searching=raw.length>0;let list=D.filter(c=>queryMatch(c,raw)&&(searching?true:(catMatch(c)&&subMatch(c)))&&dayMatch(c));list=list.map(c=>({c,g:searching?searchGroup(c):groupFor(c)})).sort((a,b)=>a.g[0]-b.g[0]||a.c.t.localeCompare(b.c.t,'pt-BR'));let out='',last='__';for(const x of list){const label=x.g[1];if(label&&label!==last){out+=`<div class="group-title">${esc(label)}${GROUP_DESCS[label]?`<small>${esc(GROUP_DESCS[label])}</small>`:''}</div>`;last=label}out+=cardHTML(x.c)}cardsEl.innerHTML=out;fb.classList.toggle('search-mode',searching);if(searching){fb.innerHTML=`🔎 <b>${list.length}</b> ${list.length===1?'resultado':'resultados'} em todo o guia para “${esc(raw)}”`;guideTitle.textContent=`🔎 Pesquisa: “${raw}”`;guideSub.textContent='A busca ignora a categoria selecionada e procura em todo o MA na Rota.';subwrap.hidden=true;searchHintEl.innerHTML='Pesquisa ativa em <strong>todo o guia</strong>. Limpe o campo para voltar aos filtros.'}else{fb.innerHTML=`<b>${list.length}</b> ${list.length===1?'resultado':'resultados'}`+(sub!=='all'?` · filtro: <b>${esc((SUBS[cat]||[]).find(x=>x[0]===sub)?.[1]||sub)}</b>`:'');updateGuide();searchHintEl.innerHTML='A pesquisa procura em <strong>todo o MA na Rota</strong>, independentemente da categoria selecionada.'}clearSearchEl.hidden=!searching;emptyEl.style.display=list.length?'none':'block';bindFav();if(go)cardsEl.scrollIntoView({behavior:'smooth',block:'start'})}
function updateGuide(){const names={destaques:['⭐ Destaques','Uma seleção curta para começar sem se perder entre todas as opções.'],turismo:['📍 Conhecer São Luís','Pontos históricos, praias, museus, cultura e passeios.'],comer:['🍽️ Comer & beber em São Luís','Restaurantes e paradas organizados por tipo e região.'],noite:['🌙 Noite em São Luís','Reggae, samba, pagode, seresta, pubs e bares.'],reggae:['🎶 Reggae em São Luís','Museu, casas e espaços ligados à cultura reggae.'],criancas:['👨‍👩‍👧 São Luís com crianças','Passeios para famílias e alternativas para diferentes horários.'],lendas:['👻 Lendas de São Luís','Serpente Encantada, Ana Jansen, Manguda, Olho d’Água e outras histórias.'],maranhao:['🌴 Conheça o Maranhão','Destinos organizados por região, com Tutóia e Lagoa do Cassó em destaque.'],all:['🗂️ Guia completo','Todas as indicações cadastradas no MA na Rota.']};const v=names[cat]||names.all;guideTitle.textContent=v[0];guideSub.textContent=v[1]}
function activateCategory(newCat,newSub='all',go=true){if(q.value.trim())q.value='';clearSearchEl.hidden=true;cat=newCat;sub=newSub;document.querySelectorAll('#mainCategories [data-f]').forEach(b=>b.classList.toggle('on',b.dataset.f===cat));renderSubfilters();render(go)}
document.querySelectorAll('#mainCategories [data-f]').forEach(b=>b.onclick=()=>activateCategory(b.dataset.f,'all',true));document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-day]').forEach(x=>x.classList.remove('on'));b.classList.add('on');day=b.dataset.day==='today'?String(new Date().getDay()):b.dataset.day;render(true)});document.querySelectorAll('[data-ma-sub]').forEach(b=>b.onclick=()=>activateCategory('maranhao',b.dataset.maSub,true));q.addEventListener('input',()=>{renderSubfilters();render(false)});q.addEventListener('keydown',e=>{if(e.key==='Escape'){q.value='';renderSubfilters();render(false);q.blur()}});clearSearchEl.onclick=()=>{q.value='';renderSubfilters();render(false);q.focus()};
const dt=new Date(),h=dt.getHours();todayTextEl.textContent='Hoje é '+dt.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'2-digit'})+'. Sugestões pelo horário do seu aparelho.';if(h<12){n1El.textContent='🏛️ Agora: Centro Histórico';t1El.textContent='Patrimônio, museus, Mercado das Tulhas e ruas históricas.';n2El.textContent='🍽️ Depois: almoço';t2El.textContent='Abra Comer & beber e escolha por perfil.'}else if(h<17){n1El.textContent='🍽️ Agora: sabores da Ilha';t1El.textContent='Almoço, café ou sorvete.';n2El.textContent='🌅 Depois: pôr do sol';t2El.textContent='Espigão, São Marcos ou Praça Pôr do Sol.'}else{n1El.textContent='🌅 Agora: fim de tarde';t1El.textContent='Orla e pôr do sol antes do jantar.';n2El.textContent='🌙 Depois: noite';t2El.textContent='Reggae, samba, seresta ou jantar.'}
const KEY='manarota-favs4';function favs(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}}function bindFav(){const fs=favs();document.querySelectorAll('.item').forEach(c=>{const data=D[+c.dataset.i],bt=c.querySelector('.fav');if(!data||!bt)return;const on=fs.includes(data.t);bt.textContent=on?'★':'☆';bt.classList.toggle('on',on);bt.onclick=()=>{let z=favs();z=z.includes(data.t)?z.filter(x=>x!==data.t):[...z,data.t];localStorage.setItem(KEY,JSON.stringify(z));renderFav();render(false)}});renderFav()}function renderFav(){const f=favs();favListEl.innerHTML=f.length?f.map(x=>'<div class="route">⭐ '+esc(x)+'</div>').join(''):'Nenhum favorito ainda.'}
async function cp(text,bt){try{await navigator.clipboard.writeText(text);const o=bt.textContent;bt.textContent='✅ Copiado';setTimeout(()=>bt.textContent=o,1500)}catch(e){prompt('Copie:',text)}}copyKeyEl.onclick=()=>cp(pixKeyEl.textContent,copyKeyEl);shareEl.onclick=async()=>{const data={title:'MA na Rota',text:'Guia independente de São Luís e do Maranhão.',url:location.href};try{if(navigator.share)await navigator.share(data);else cp(location.href,shareEl)}catch(e){}};nearEl.onclick=()=>{if(!navigator.geolocation){alert('Localização indisponível.');return}nearEl.textContent='📍 Localizando…';navigator.geolocation.getCurrentPosition(p=>{window.open('https://www.google.com/maps/search/pontos+turisticos+restaurantes+cafes/@'+p.coords.latitude+','+p.coords.longitude+',14z','_blank');nearEl.textContent='📍 Perto de mim'},()=>{nearEl.textContent='📍 Perto de mim';alert('Permita a localização para usar este recurso.')},{timeout:8000,maximumAge:300000})};
updateMainCounts();renderSubfilters();render(false);