(()=>{
const U=window.MA_UI||{},el=id=>document.getElementById(id),D=(window.MA_CARDS||[]).map((c,i)=>({...c,_i:i}));
const cards=el('cards'),q=el('q'),form=el('searchForm'),clear=el('clearSearch'),feedback=el('feedback'),empty=el('empty'),subwrap=el('subwrap'),subchips=el('subchips'),subhead=el('subhead'),guideTitle=el('guideTitle'),guideSub=el('guideSub'),favList=el('favList');
let cat='destaques',sub='all',day='all';
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),esc=s=>(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const textOf=c=>norm([c.t,c.d,c.g,c.h,c.p].join(' ')),has=(c,a)=>a.some(w=>textOf(c).includes(norm(w)));
const FEATURED=['Centro Histórico','Historic Center','Palácio dos Leões','Museu do Reggae','Reggae Museum','Mercado das Tulhas','Espigão Costeiro','Parque do Rangedor','Cabana do Sol','Flor de Vinagreira','Barraca da Marcela','Bar do Nelson','Lençóis Maranhenses','Alcântara','Tutóia','Lagoa do Cassó','Chapada das Mesas','Imperatriz'];
function matchesCat(c,k){const t=norm(c.g).split(/\s+/);if(k==='destaques')return FEATURED.some(x=>norm(c.t).includes(norm(x)));if(k==='all')return true;if(k==='reggae')return t.includes('reggae');if(k==='noite')return t.includes('noite')||t.includes('reggae');if(k==='lendas')return t.includes('lendas')||has(c,['serpente','ana jansen','manguda','olho dagua']);return t.includes(k)}
const M={centro:['centro','praia grande','reviver'],cultura:['cultura','historia','patrimonio','igreja','afro','quilombo'],museu:['museu'],praia:['praia','orla','litoranea'],'por-do-sol':['por-do-sol','por do sol'],lendas:['lendas','serpente','ana jansen','manguda'],ilha:['olho dagua','mae dagua'],regional:['maranhense','regional','nordestino','cuxa','jucara'],frutos:['frutos mar','peixe','camarao','bacalhau','marisco'],caranguejo:['caranguejo','caranguejada'],orla:['litoranea','calhau','ponta dareia','ponta farol','sao marcos'],cafe:['cafe','caffè'],sorvete:['sorvete','gelato'],casal:['casal'],familia:['familia','grupo'],reggae:['reggae'],samba:['samba','pagode'],pub:['pub','rock','blues','musica ao vivo'],parque:['parque'],indoor:['shopping','indoor','chuva','danny'],perto:['alcantara','raposa','ribamar','paco lumiar','grande ilha'],lencois:['lencois','barreirinhas','santo amaro','atins'],delta:['tutoia','delta','araioses','agua doce','paulino neves','arpoador'],casso:['casso','primeira cruz'],munim:['morros','munim','rio una'],chapada:['chapada','carolina','riachao'],imperatriz:['imperatriz'],guaras:['guaras','cururupu','guimaraes','floresta dos guaras']};
const matchesSub=(c,k)=>k==='all'||(M[k]||[]).some(w=>textOf(c).includes(norm(w))),dayMatch=c=>day==='all'||(c.y||'all')==='all'||String(c.y).split(',').includes(day),queryMatch=(c,r)=>{const z=textOf(c),ts=norm(r).trim().split(/\s+/).filter(Boolean);return !ts.length||ts.every(t=>z.includes(t))};
function groupFor(c,searching){const g=U.groups||{};if(searching){const t=norm(c.g).split(/\s+/);if(t.includes('maranhao')&&!t.includes('sao'))return[4,g.searchMA];if(t.includes('comer')||t.includes('cafe')||t.includes('sorvete'))return[2,g.searchFood];if(t.includes('noite')||t.includes('reggae'))return[3,g.searchNight];if(t.includes('lendas'))return[1,g.searchLegends];return[0,g.searchSL]}
if(cat==='maranhao'){if(has(c,['imperatriz']))return[6,g.imperatriz];if(has(c,['casso','primeira cruz']))return[3,g.casso];if(has(c,['tutoia','delta','araioses','agua doce','paulino neves','arpoador']))return[2,g.delta];if(has(c,['lencois','barreirinhas','santo amaro','atins']))return[1,g.lencois];if(has(c,['alcantara','raposa','ribamar','paco lumiar','grande ilha']))return[0,g.near];if(has(c,['morros','munim','rio una']))return[4,g.munim];if(has(c,['chapada','carolina','riachao']))return[5,g.chapada];if(has(c,['guaras','cururupu','guimaraes']))return[7,g.guaras];return[8,g.otherMA]}
if(cat==='comer'){if(has(c,['cafe','caffè']))return[5,g.cafes];if(has(c,['sorvete','gelato']))return[6,g.ice];if(has(c,['caranguejo','caranguejada']))return[2,g.crab];if(has(c,['maranhense','regional','cuxa','jucara']))return[0,g.regional];if(has(c,['frutos mar','peixe','camarao','bacalhau']))return[1,g.seafood];if(has(c,['centro','praia grande','reviver']))return[3,g.foodCenter];if(has(c,['litoranea','calhau','ponta dareia','ponta farol']))return[4,g.foodCoast];return[7,g.otherFood]}
if(cat==='turismo'){if(has(c,['museu']))return[1,g.museums];if(has(c,['praia','orla','litoranea']))return[3,g.beaches];if(has(c,['por-do-sol','por do sol']))return[4,g.sunset];if(has(c,['lendas','serpente','ana jansen','manguda']))return[5,g.legends];if(has(c,['centro','historia','patrimonio','cultura']))return[0,g.history];return[6,g.otherSL]}
if(cat==='lendas')return has(c,['olho dagua','mae dagua'])?[1,g.islandLegends]:[0,g.centerLegends];
if(cat==='noite'||cat==='reggae'){if(has(c,['reggae']))return[0,g.reggae];if(has(c,['samba','pagode']))return[1,g.samba];if(has(c,['seresta']))return[2,g.seresta];if(has(c,['pub','rock','blues']))return[3,g.pubs];return[4,g.otherNight]}return[0,'']}
function cardHTML(c){return `<article class="card item" data-i="${c._i}">${c.s?`<span class="st${c.a?' alert':''}">${esc(c.s)}</span>`:''}<button class="fav" type="button" aria-label="${esc(U.favorite||'Favorite')}">☆</button><h3>${esc(c.t)}</h3><p>${esc(c.d)}</p>${c.h?`<div class="hrs">${esc(c.h)}</div>`:''}${c.p?`<div class="tip">${esc(c.p)}</div>`:''}<div class="acts">${(c.l||[]).map(x=>`<a class="btn" target="_blank" rel="noopener" href="${esc(x.url)}">${esc(x.label)}</a>`).join('')}</div></article>`}
function renderSub(){if(q.value.trim()){subwrap.hidden=true;return}const defs=(U.subs||{})[cat]||[];subwrap.hidden=!defs.length;if(!defs.length){sub='all';return}subhead.textContent=(U.subheads||{})[cat]||U.refine;subchips.innerHTML=defs.map(([k,l])=>`<button class="chip${k===sub?' on':''}" type="button" data-sub="${k}">${l}<span class="sub-count">${D.filter(c=>matchesCat(c,cat)&&matchesSub(c,k)).length}</span></button>`).join('');subchips.querySelectorAll('[data-sub]').forEach(b=>b.onclick=()=>{sub=b.dataset.sub;renderSub();render(true)})}
function updateGuide(){const v=(U.guides||{})[cat]||(U.guides||{}).all||['',''];guideTitle.textContent=v[0];guideSub.textContent=v[1]}
function render(go=false){const raw=q.value.trim(),searching=!!raw;let list=D.filter(c=>queryMatch(c,raw)&&(searching||matchesCat(c,cat)&&matchesSub(c,sub))&&dayMatch(c));list=list.map(c=>({c,g:groupFor(c,searching)})).sort((a,b)=>a.g[0]-b.g[0]||a.c.t.localeCompare(b.c.t,U.locale||'en'));let out='',last='__';for(const x of list){const lab=x.g[1];if(lab&&lab!==last){out+=`<div class="group-title">${esc(lab)}</div>`;last=lab}out+=cardHTML(x.c)}cards.innerHTML=out;feedback.innerHTML=searching?`🔎 <b>${list.length}</b> ${list.length===1?U.result:U.results} — “${esc(raw)}”`:`<b>${list.length}</b> ${list.length===1?U.result:U.results}`;clear.hidden=!searching;empty.style.display=list.length?'none':'block';if(searching){guideTitle.textContent=`🔎 ${U.searchTitle}: “${raw}”`;guideSub.textContent=U.searchDesc;subwrap.hidden=true}else{updateGuide();renderSub()}bindFav();if(go)cards.scrollIntoView({behavior:'smooth',block:'start'})}
function activate(k,s='all',go=true){q.value='';clear.hidden=true;cat=k;sub=s;document.querySelectorAll('[data-f]').forEach(b=>b.classList.toggle('on',b.dataset.f===cat));renderSub();render(go)}
document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>activate(b.dataset.f));document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-day]').forEach(x=>x.classList.remove('on'));b.classList.add('on');day=b.dataset.day==='today'?String(new Date().getDay()):b.dataset.day;render(true)});document.querySelectorAll('[data-ma-sub]').forEach(b=>b.onclick=()=>activate('maranhao',b.dataset.maSub));document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>{q.value=b.dataset.search;render(true)});form.addEventListener('submit',e=>{e.preventDefault();render(true)});q.addEventListener('input',()=>render(false));clear.onclick=()=>{q.value='';render(false);q.focus()};
const KEY='manarota-favs-'+(U.code||'xx');function favs(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}}function bindFav(){const fs=favs();document.querySelectorAll('.item').forEach(c=>{const d=D[+c.dataset.i],b=c.querySelector('.fav');if(!d||!b)return;const on=fs.includes(d.t);b.textContent=on?'★':'☆';b.classList.toggle('on',on);b.onclick=()=>{let z=favs();z=z.includes(d.t)?z.filter(x=>x!==d.t):[...z,d.t];localStorage.setItem(KEY,JSON.stringify(z));renderFav();render(false)}});renderFav()}function renderFav(){const f=favs();favList.innerHTML=f.length?f.map(x=>`<div class="route">⭐ ${esc(x)}</div>`).join(''):U.noFavorites}
const dt=new Date(),h=dt.getHours();el('todayText').textContent=U.todayDate.replace('{date}',dt.toLocaleDateString(U.locale||'en',{weekday:'long',day:'2-digit',month:'2-digit'}));if(h<12){el('n1').textContent=U.morning1;el('t1').textContent=U.morning1d;el('n2').textContent=U.morning2;el('t2').textContent=U.morning2d}else if(h<17){el('n1').textContent=U.afternoon1;el('t1').textContent=U.afternoon1d;el('n2').textContent=U.afternoon2;el('t2').textContent=U.afternoon2d}else{el('n1').textContent=U.evening1;el('t1').textContent=U.evening1d;el('n2').textContent=U.evening2;el('t2').textContent=U.evening2d}
el('copyKey').onclick=async()=>{try{await navigator.clipboard.writeText(el('pixKey').textContent);el('copyKey').textContent=U.copied;setTimeout(()=>el('copyKey').textContent=U.copyPix,1600)}catch(e){prompt(U.copyPrompt,el('pixKey').textContent)}};el('share').onclick=async()=>{const d={title:'MA na Rota',text:U.shareText,url:location.href};try{if(navigator.share)await navigator.share(d);else await navigator.clipboard.writeText(location.href)}catch(e){}};el('near').onclick=()=>{if(!navigator.geolocation){alert(U.locationUnavailable);return}navigator.geolocation.getCurrentPosition(p=>window.open(`https://www.google.com/maps/search/tourist+attractions+restaurants/@${p.coords.latitude},${p.coords.longitude},14z`,'_blank'),()=>alert(U.locationDenied),{timeout:8000,maximumAge:300000})};
document.querySelectorAll('#mainCategories [data-f]').forEach(b=>{const s=document.createElement('span');s.className='cat-count';s.textContent=D.filter(c=>matchesCat(c,b.dataset.f)).length;b.appendChild(s)});renderSub();render();
})();